### ISSUE TITLE
Signal Gate Process not accepting negative for signal offset

### ISSUE THREAD

**Issue by ksaye** [Azure/lva-edge-vscode-extension#83]
When using VS Code, the UI does not allow a negative in the "Activation signal offset":

![image](https://user-images.githubusercontent.com/15837044/112660921-fb892200-8e23-11eb-971d-67c9e2906e22.png)

Even though the help says it can take -60 tp 60:

![image](https://user-images.githubusercontent.com/15837044/112660986-0c399800-8e24-11eb-8bb7-8cad7e4f87f7.png)

VS Code:
![image](https://user-images.githubusercontent.com/15837044/112661113-283d3980-8e24-11eb-8404-38106371fd51.png)

LVA on IoT Edge Extension version: 0.1.1

**Comment by giakas** [comment]
Thanks for reporting, looking in to it.

**Comment by giakas** [comment]
this has been fixed in last release
